apiVersion: v1
kind: Namespace
metadata:
  name: mlops
  labels:
    name: mlops
    purpose: data-platform
---
apiVersion: v1
kind: Namespace
metadata:
  name: monitoring
  labels:
    name: monitoring
    purpose: observability
