apiVersion: apps/v1
kind: Deployment
metadata:
  name: spark
  namespace: mlops
spec:
  replicas: 1
  selector:
    matchLabels:
      app: spark
  template:
    metadata:
      labels:
        app: spark
    spec:
      containers:
        - name: spark
          image: bitnami/spark:latest
          env:
            - name: SPARK_MODE
              value: master
          ports:
            - containerPort: 7077   # cluster
            - containerPort: 8080   # UI