apiVersion: apps/v1
kind: Deployment
metadata:
  name: nessie
  namespace: mlops
spec:
  replicas: 1
  selector:
    matchLabels:
      app: nessie
  template:
    metadata:
      labels:
        app: nessie
    spec:
      containers:
        - name: nessie
          image: ghcr.io/projectnessie/nessie:0.107.5-java
          env:
            - name: QUARKUS_DATASOURCE_JDBC_URL
              value: jdbc:postgresql://postgresql:5432/nessie
            - name: QUARKUS_DATASOURCE_USERNAME
              value: nessie
            - name: QUARKUS_DATASOURCE_PASSWORD
              value: nessie
          ports:
            - containerPort: 19120
          readinessProbe:
            httpGet:
              path: /q/health/ready
              port: 19120
            initialDelaySeconds: 10
            periodSeconds: 10
            timeoutSeconds: 3
            failureThreshold: 12
          livenessProbe:
            httpGet:
              path: /q/health/live
              port: 19120
            initialDelaySeconds: 30
            periodSeconds: 20
            timeoutSeconds: 3
            failureThreshold: 6