{{- if .Values.enabled.sparkOperator }}
apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: spark-operator
  {{- include "platformApps.appMetadata" . | nindent 2 }}
  annotations:
    argocd.argoproj.io/sync-wave: "5"
spec:
  project: {{ .Values.project }}
  sources:
    - repoURL: https://kubeflow.github.io/spark-operator
      chart: spark-operator
      targetRevision: {{ .Values.versions.sparkOperator }}
      helm:
        valueFiles:
          - $values/platform/spark-operator/values.yaml
    - repoURL: {{ .Values.repoURL }}
      targetRevision: {{ .Values.targetRevision }}
      ref: values
  destination:
    server: {{ .Values.destinationServer }}
    namespace: {{ .Values.namespaces.platform }}
  {{- include "platformApps.syncPolicy" . | nindent 2 }}
{{- end }}
